openapi: 3.0.3
info:
  version: 1.0.0
  title: Harmoniq App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for articles, authentication, and user management

tags:
  - name: Auth
    description: Auth operations.
  - name: User
    description: User profiles and avatars
  - name: Articles
    description: Managing articles
  - name: Categories
    description: Article categories
servers:
  - url: http://localhost:3000
  - url: https://harmoniq-6.onrender.com
paths:
  /auth/register:
    $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    $ref: ../swagger/paths/auth/refresh.yaml

  /articles:
    get:
      $ref: ../swagger/paths/articles/get.yaml
    post:
      $ref: ../swagger/paths/articles/post.yaml

  /articles/{articleId}:
    get:
      $ref: ../swagger/paths/articles/{articleId}/get.yaml
    patch:
      $ref: ../swagger/paths/articles/{articleId}/patch.yaml
    delete:
      $ref: ../swagger/paths/articles/{articleId}/delete.yaml

  /users/authors:
    get:
      $ref: ../swagger/paths/users/authors/get.yaml

  /users/authors/{id}:
    get:
      $ref: ../swagger/paths/users/authors/{id}/get.yaml

  /users/authors/{id}/articles:
    get:
      $ref: ../swagger/paths/users/authors/{id}/articles/get.yaml

  /users/me:
    get:
      $ref: ../swagger/paths/users/me/get.yaml

  /users/me/saved-articles:
    get:
      $ref: ../swagger/paths/users/me/saved-articles/get.yaml

  /users/me/saved-articles/{articleId}:
    delete:
      $ref: ../swagger/paths/users/me/saved-articles/{articleId}/delete.yaml
    post:
      $ref: ../swagger/paths/users/me/saved-articles/{articleId}/post.yaml

  /users/me/created:
    get:
      $ref: ../swagger/paths/users/me/created-articles/get.yaml

  /categories:
    get:
      $ref: ../swagger/paths/categories/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    AuthUser:
      $ref: '../swagger/components/schemas/auth.yaml#/AuthUser'
    LoginResponse:
      $ref: '../swagger/components/schemas/auth.yaml#/LoginResponse'
    RefreshTokenRequest:
      $ref: '../swagger/components/schemas/auth.yaml#/RefreshTokenRequest'
    RegisterUser:
      $ref: '../swagger/components/schemas/auth.yaml#/RegisterUser'
    Article:
      $ref: '../swagger/components/schemas/articles.yaml#'

  responses:
    '400':
      $ref: '../swagger/components/responses/400.yaml'
    '401':
      $ref: '../swagger/components/responses/401.yaml'

security:
  - bearerAuth: []
