openapi: 3.1.0
info:
  version: 1.0.0
  title: Harmoniq App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for articles, authentication, and user management
tags:
  - name: Auth
    description: Auth operations.
  - name: User
    description: User profiles and avatars
  - name: Articles
    description: Managing articles
  - name: Categories
    description: Article categories
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /articles:
    get:
      $ref: ../swagger/paths/articles/get.yaml
    post:
      $ref: ../swagger/paths/articles/post.yaml
  /articles/{articleId}:
    get:
      $ref: ../swagger/paths/articles/{articleId}/get.yaml
    patch:
      $ref: ../swagger/paths/articles/{articleId}/patch.yaml
    delete:
      $ref: ../swagger/paths/articles/{articleId}/delete.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/refresh.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/register.yaml
  /users/profile:
    get:
      $ref: ../swagger/paths/users/profile/get.yaml
  /users/saved:
    get:
      $ref: ../swagger/paths/users/saved/get.yaml
    post:
      $ref: ../swagger/paths/users/saved/post.yaml
  /users/saved/{articleId}:
    delete:
      $ref: ../swagger/paths/users/saved/{articleId}/delete.yaml
  /users/created:
    get:
      $ref: ../swagger/paths/users/created/get.yaml
  /categories:
    get:
      $ref: ../swagger/paths/categories/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
